In [7]:
import pandas as pd
import pandasql as ps # type: ignore
from natsort import natsorted # type: ignore
import os

In [8]:
path = '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs'
files = os.listdir(path)
files = [f for f in files if f.endswith('.csv')]
files = natsorted(files)
files = [os.path.join(path, f) for f in files]
files

['/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/1.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/2.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/3.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/4.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/5.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/6.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/7.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/8.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/9.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/10.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/11.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/12.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/13.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/14.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/15.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/16.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/17.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/18.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/19.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/20.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/21.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/22.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/23.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/24.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/37.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/43.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/44.csv',
 '/Users/PhanithLIM/Documents/05.Dataset/Speech Recognition/processing/WMC-Internation/clean-logs/45.csv']

In [9]:
list_df = [ pd.read_csv(f) for f in files ]
df = pd.concat(list_df, axis=0)
df = df.reset_index(drop=True)
df = df.drop(columns=['id', 'link'])
df.head(10)

,title,date,author,speaker
0,របាយការណ៍រកឃើញថា ការរាយការណ៍អំពីប្រទេសចិននាំឱ្...,"April 23, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
1,រដ្ឋសភាអាមេរិកអនុម័តកញ្ចប់ជំនួយ ៩៥ពាន់លានដុល្ល...,"April 22, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
2,កម្មករចំណាកស្រុកដែលជួយកសាងចិនសម័យទំនើបនៅតែមិនអ...,"April 9, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
3,ក្នុង​​​ដំណើរ​ថយ​ក្រោយ​សម្រាប់​លោក Erdogan ក្រ...,"April 4, 2024",គីម ចាន់ចាវ,កញ្ញា កែវ សុជាតា
4,ច្បាប់រៀបអាពាហ៍ពិពាហ៍របស់ក្រុម LGBTI+ នៅថៃ ត្រ...,"March 28, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
5,អាជ្ញាធរជប៉ុនសង្ស័យ ផលិតផលបំប៉នសុខភាពមួយចំនួន ...,"March 28, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
6,អាជ្ញាធរខេត្តភូកេតប្រទេសថៃដកហូតសិទ្ធិគ្រប់គ្រង...,"March 12, 2024",ឡាក់ ច័ន្ទតារា,កញ្ញា សៃ ចន្ធី
7,រដ្ឋមន្រ្តីការពារជាតិឥណ្ឌូនេស៊ីត្រូវដំឡើងជានាយ...,"February 29, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា
8,រកឃើញក្មេងស្រីអាយុ៣ឆ្នាំនៅមានជីវិត ក្នុងគ្រោះប...,"February 13, 2024",កែវ សុជាតា,កញ្ញា សៃ ចន្ធី
9,UNICEF៖ កុមារជិត ៧ម៉ឺននាក់រួចផុតពីសេចក្តីស្លាប...,"February 12, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា

In [10]:
q1 = '''
SELECT 
    *,
    CASE 
        WHEN speaker LIKE 'កញ្ញា%' THEN 'ស្រី'  
        ELSE 'ប្រុស'
    END AS gender
FROM df; 
'''
df = ps.sqldf(q1, locals())
df.head(10)

,title,date,author,speaker,gender
0,របាយការណ៍រកឃើញថា ការរាយការណ៍អំពីប្រទេសចិននាំឱ្...,"April 23, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
1,រដ្ឋសភាអាមេរិកអនុម័តកញ្ចប់ជំនួយ ៩៥ពាន់លានដុល្ល...,"April 22, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
2,កម្មករចំណាកស្រុកដែលជួយកសាងចិនសម័យទំនើបនៅតែមិនអ...,"April 9, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
3,ក្នុង​​​ដំណើរ​ថយ​ក្រោយ​សម្រាប់​លោក Erdogan ក្រ...,"April 4, 2024",គីម ចាន់ចាវ,កញ្ញា កែវ សុជាតា,ស្រី
4,ច្បាប់រៀបអាពាហ៍ពិពាហ៍របស់ក្រុម LGBTI+ នៅថៃ ត្រ...,"March 28, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
5,អាជ្ញាធរជប៉ុនសង្ស័យ ផលិតផលបំប៉នសុខភាពមួយចំនួន ...,"March 28, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
6,អាជ្ញាធរខេត្តភូកេតប្រទេសថៃដកហូតសិទ្ធិគ្រប់គ្រង...,"March 12, 2024",ឡាក់ ច័ន្ទតារា,កញ្ញា សៃ ចន្ធី,ស្រី
7,រដ្ឋមន្រ្តីការពារជាតិឥណ្ឌូនេស៊ីត្រូវដំឡើងជានាយ...,"February 29, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី
8,រកឃើញក្មេងស្រីអាយុ៣ឆ្នាំនៅមានជីវិត ក្នុងគ្រោះប...,"February 13, 2024",កែវ សុជាតា,កញ្ញា សៃ ចន្ធី,ស្រី
9,UNICEF៖ កុមារជិត ៧ម៉ឺននាក់រួចផុតពីសេចក្តីស្លាប...,"February 12, 2024",កែវ សុជាតា,កញ្ញា កែវ សុជាតា,ស្រី

In [11]:
q2 = '''
SELECT COUNT(*) AS count_audio, speaker, 
    CASE 
        WHEN speaker LIKE 'កញ្ញា%' THEN 'ស្រី'
        ELSE 'ប្រុស'
    END AS gender 
FROM df
GROUP BY speaker
'''
result = ps.sqldf(q2, locals())
result

    count_audio             speaker gender
0            70    កញ្ញា កែវ សុជាតា   ស្រី
1             1     កញ្ញា គុជ សីកុល   ស្រី
2            18    កញ្ញា គុជ ស៊ីកុល   ស្រី
3             9   កញ្ញា ងិន ស៊ាងលីម   ស្រី
4            29      កញ្ញា សៃ ចន្ធី   ស្រី
5             2     លោក គីម ចាន់ចារ  ប្រុស
6             7     លោក គីម ចាន់ចាវ  ប្រុស
7             1          លោក ឆេងលាភ  ប្រុស
8             1    លោក ជុំ កត់ឧត្តម  ប្រុស
9             1       លោក ទាត់ សុខា  ប្រុស
10            1       លោក ទាវ វិឆាត  ប្រុស
11            2      លោក យិប ឆេងលាប  ប្រុស
12            1   លោក ហុង សេរីហ្វុង  ប្រុស
13            8  លោក ឡាក់ ច័ន្ទតារា  ប្រុស
14            4          លោក ឯម មាឃ  ប្រុស

In [12]:
q3 = f'''
SELECT COUNT(*) AS count, gender
FROM ({q2}) AS derived_table
GROUP BY gender;
'''
result = ps.sqldf(q3, locals())
result

   count gender
0     10  ប្រុស
1      5   ស្រី